### ISSUE TITLE
No visualizer pops up when running the demo, is this supposed to be like that?

### ISSUE THREAD

**Issue by SquirminatorHotHead** [hoangthien94/ORB_SLAM2_CUDA#10]
No visualizer pops up when running the demo, is this supposed to be like that? But the SLAM procedure is finished. Test on Nvidia Jetson Xavier Dev Kit.

**Comment by thien94** [comment]
Hi, if you are using ROS demo then yes, the Viewer is disabled by default. Here's the full command to launch this node with Viewer enabled: 
```
roslaunch /path/to/ORB_SLAM2_CUDA/Examples/ROS/ORB_SLAM2_CUDA/launch/ros_mono.launch bUseViewer:=true
```

**Comment by SquirminatorHotHead** [comment]
@hoangthien94 Thank you for your reply. I was running the TUM1 dataset, no viewer, but the rest is totally fine.

**Comment by SquirminatorHotHead** [comment]
@hoangthien94  Here is all I get from the terminal, it seems like the viewer was disabled or the Pangolin doesn't work. I have switched  to the old version of Pangolin and also changed the code, I mean I tried many related solutions but still not working. 

$ ./build/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUM1.yaml Data/rgbd_dataset_freiburg1_desk

ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!


Camera Parameters: 
- fx: 517.306
- fy: 516.469
- cx: 318.643
- cy: 255.314
- k1: 0.262383
- k2: -0.953104
- k3: 1.16331
- p1: -0.005358
- p2: 0.002628
- fps: 30
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

-------
Start processing sequence ...
Images in the sequence: 613

New Map created with 103 points
-------

median tracking time: 0.0275838
mean tracking time: 0.0304826

Saving keyframe trajectory to KeyFrameTrajectory.txt ...

trajectory saved!

**Comment by thien94** [comment]
Hi @anakin0620, sorry for the late reply.

This is actually a bug in the non-ROS code that I did not notice. I have fixed the bug, you can pull the latest code and try the command with one more argument at the end:

```
$ ./build/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUM1.yaml Data/rgbd_dataset_freiburg1_desk true
``` 
The `true` argument corresponds to `bUseViewer`, which would enable/disable Viewer, same as the ROS counterpart. 

Let me know if it works for you.

**Comment by SquirminatorHotHead** [comment]
Thank you @hoangthien94, I will test it later and let you know if it’s working.

**Comment by SquirminatorHotHead** [comment]
The bug has been fixed, thanks @hoangthien94
