### ISSUE TITLE
Change to CMakeLists.txt

### ISSUE THREAD

**Issue by griz1112** [hoangthien94/ORB_SLAM2_CUDA#3]
The CMakeLists.txt in the Examples/ROS/ORB_SLAM2_CUDA directory needs to be changed otherwise the ROS programs link to the non gpu enabled lib. Line 60 libORB_SLAM2 needs to be libORB_SLAM2_CUDA.so.

**Comment by thien94** [comment]
Thanks Dan. I didn't change the lib name created after the build (libORB_SLAM2.so as in the original), so actually libORB_SLAM2.so in the lib folder is the CUDA version. I have changed the name to clear the confusion.
