### ISSUE TITLE
Could you explain which part of SLAM was enhanced by GPU?

### ISSUE THREAD

**Issue by YiChenCityU** [hoangthien94/ORB_SLAM2_CUDA#4]
Hi, I am doing SLAM on GPU recently. I am new to this. Could you explain how the GPU speed up the SLAM? Thanks very much.

**Comment by thien94** [comment]
Hi, I am not an expert in this domain but here's my understanding:

- With the present of GPU you can accelerate sequential programs (in this case `ORB-SLAM2`) by offloading some sections of the code to GPU, while the rest of the code still uses CPU. GPU can run thousands of threads simultaneously, allowing for faster processing than a CPU while being more power and cost efficient. Below is a picture showing how GPU-acceleration works.

![image](https://user-images.githubusercontent.com/12378920/45941981-1db34680-c013-11e8-8a2c-26f048815deb.png)

- In `ORB-SLAM2`, we have three main threads: `Tracking`, `Local Mapping`, `Loop Closing`, with `Tracking` thread being the biggest bottleneck: new image frame cannot be processed until the `Tracking` thread is finished with the last frame. Thus it is the main focus for some of the enhancement works on `ORB-SLAM2`.
Of course, every `SLAM` algorithm is different so you must determine the bottleneck in your case and focus on that one to put GPU-acceleration into effect.

- This repo uses the GPU-optimization work by [yunchih](https://github.com/yunchih/ORB-SLAM2-GPU2016-final), which improves several processes in the `Tracking` thread, i.e. `FAST corner detection` and `ORB feature extraction`, with CUDA APIs. In general, where possible you can parallelize all OpenCV functions by replacing them with OpenCV CUDA functions.

I would recommend you read the authors' report [here](https://yunchih.github.io/ORB-SLAM2-GPU2016-final/) if you want to learn the details of their work.

Hope this helps.

**Comment by YiChenCityU** [comment]
Thanks very much. 
But I have learned that GPU also can do the matching in SLAM . Have you tried it in GPU?

**Comment by thien94** [comment]
I have not tried that personally. There are some papers that might be helpful for you: 
[GPU-Accelerated Real-Time Stereo Matching](http://www.cse.chalmers.se/~uffe/xjobb/PeterHillerstr%C3%B6mMastersThesis_2017-06-12.pdf)
[Parallel, Real-Time Visual SLAM](https://www.cs.unc.edu/~bclipp/papers/clipp2010_parallel_RT_VSLAM.pdf).

**Comment by YiChenCityU** [comment]
Great! Thanks very much.
