### ISSUE TITLE
Without ROS

### ISSUE THREAD

**Issue by nalinraut** [hoangthien94/ORB_SLAM2_CUDA#5]
Hi, 
Can does this repo work for ORB_SLAM2 without ROS?

**Comment by 66loveslife** [comment]
Hello，
I can build the build.sh .when I try to use ORB_slam_cuda to run dateset,it terminal came error.
*******************************
ubuntu@ubuntu-Precision-Tower-5810:~/ORB_SLAM2_CUDA-master$ ./build/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM1.yaml /home/ubuntu/ORB_SLAM2_CUDA-master/rgbd_dataset_freiburg1_room/ /home/ubuntu/ORB_SLAM2_CUDA-master/rgbd_dataset_freiburg1_room/associate.txt 

ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: RGB-D

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!


Camera Parameters: 
- fx: 517.306
- fy: 516.469
- cx: 318.643
- cy: 255.314
- k1: 0.262383
- k2: -0.953104
- k3: 1.16331
- p1: -0.005358
- p2: 0.002628
- fps: 30
- color order: RGB (ignored if grayscale)
CUDA error at /home/ubuntu/ORB_SLAM2_CUDA-master/src/cuda/Fast_gpu.cu:318 code=71(cudaErrorNotSupported) "cudaMallocManaged(&kpLoc, sizeof(short2) * maxKeypoints)" 
*****************************
Can you tell me how to solve it ? and is this program only for TX1?
Thank you very much for your help.

**Comment by thien94** [comment]
Hi, sorry for the late reply.

Yes, it can run without ROS. In that case you should run it normally as described in the [original ORB_SLAM2](https://github.com/raulmur/ORB_SLAM2#4-monocular-examples).
