### ISSUE TITLE
process has died [pid 3277, exit code 1

### ISSUE THREAD

**Issue by why-freedom** [hoangthien94/ORB_SLAM2_CUDA#9]
why@why-desktop:~$ roslaunch '/home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/launch/ros_mono.launch' 
... logging to /home/why/.ros/log/b0f0beae-7eb9-11e9-aa9a-7085c2882345/roslaunch-why-desktop-3260.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://why-desktop:41915/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    ORB_SLAM2 (ORB_SLAM2/Mono)

ROS_MASTER_URI=http://localhost:11311

WARNING: Package name "orbslamDemo" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[ORB_SLAM2-1]: started with pid [3277]

Usage: rosrun ORB_SLAM2 Mono path_to_vocabulary path_to_settings
[ORB_SLAM2-1] process has died [pid 3277, exit code 1, cmd /home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/Mono /home/why/catkin_slam_ws/src/ORB_SLAM2/Vocabulary/ORBvoc.txt /home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/myslam.yaml false true __name:=ORB_SLAM2 __log:=/home/why/.ros/log/b0f0beae-7eb9-11e9-aa9a-7085c2882345/ORB_SLAM2-1.log].
log file: /home/why/.ros/log/b0f0beae-7eb9-11e9-aa9a-7085c2882345/ORB_SLAM2-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by thien94** [comment]
I can't say for sure what is the problem here. Can you take a look into the log file (location is shown in the message)?

**Comment by why-freedom** [comment]
The log is as follows. I only added the 'pose' topic part by referring to your project, but when I run it, I get an error. . . Thanks for help
 
why@why-desktop:~/.ros/log/9ec63c9e-7ec9-11e9-aa9a-7085c2882345$ cat roslaunch-why-desktop-11960.log 
[roslaunch][INFO] 2019-05-25 16:50:58,580: Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2019-05-25 16:50:58,591: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2019-05-25 16:50:58,591: roslaunch starting with args ['/opt/ros/kinetic/bin/roslaunch', '/home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/launch/ros_mono.launch']
[roslaunch][INFO] 2019-05-25 16:50:58,592: roslaunch env is {'UPSTART_EVENTS': 'xsession started', 'XDG_SESSION_TYPE': 'x11', 'LC_PAPER': 'zh_CN.UTF-8', 'TURTLEBOT_STDR_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_stdr/maps/sparse_obstacles.yaml', 'SHELL': '/bin/bash', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'UNITY_DEFAULT_PROFILE': 'unity', 'UPSTART_INSTANCE': '', 'JOB': 'unity-settings-daemon', 'SESSION': 'ubuntu', 'XMODIFIERS': '@im=fcitx', 'TURTLEBOT_INTERACTIONS_LIST': '[turtlebot_bringup/admin.interactions, turtlebot_bringup/documentation.interactions, turtlebot_bringup/pairing.interactions, turtlebot_bringup/visualisation.interactions]', 'GTK2_MODULES': 'overlay-scrollbar', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_ADDRESS': 'zh_CN.UTF-8', 'PYTHONPATH': '/home/why/catkin_slam_ws/devel/lib/python2.7/dist-packages:/home/why/catkin_ws_practice/devel/lib/python2.7/dist-packages:/home/why/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages', 'COMPIZ_BIN_PATH': '/usr/bin/', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'QT_ACCESSIBILITY': '1', 'XDG_SESSION_ID': 'c2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-Wcfjkq9vsA', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'DESKTOP_SESSION': 'ubuntu', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'INSTANCE': '', 'TURTLEBOT_GAZEBO_WORLD_FILE': '/opt/ros/kinetic/share/turtlebot_gazebo/worlds/playground.world', 'TURTLEBOT_3D_SENSOR': 'asus_xtion_pro', 'TURTLEBOT_RAPP_PACKAGE_BLACKLIST': '[]', 'LC_NAME': 'zh_CN.UTF-8', 'XDG_MENU_PREFIX': 'gnome-', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LC_NUMERIC': 'zh_CN.UTF-8', 'TURTLEBOT_TYPE': 'turtlebot', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'TURTLEBOT_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_navigation/maps/willow-2010-02-18-0.10.yaml', 'USER': 'why', 'XDG_VTNR': '7', 'CMAKE_PREFIX_PATH': '/home/why/catkin_slam_ws/devel:/home/why/catkin_ws_practice/devel:/home/why/catkin_ws/devel:/home/why/sim_ws/devel:/opt/ros/kinetic', 'XAUTHORITY': '/home/why/.Xauthority', 'LANGUAGE': 'en', 'SESSION_MANAGER': 'local/why-desktop:@/tmp/.ICE-unix/1921,unix/why-desktop:/tmp/.ICE-unix/1921', 'SHLVL': '1', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'DISPLAY': ':0', 'CLUTTER_IM_MODULE': 'xim', 'WINDOWID': '90209485', 'GPG_AGENT_INFO': '/home/why/.gnupg/S.gpg-agent:0:1', 'XDG_SESSION_DESKTOP': 'ubuntu', 'GDMSESSION': 'ubuntu', 'UPSTART_JOB': 'unity7', 'TURTLEBOT_GAZEBO_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_gazebo/maps/playground.yaml', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'ROS_PACKAGE_PATH': '/home/why/catkin_slam_ws/src:/home/why/catkin_ws_practice/src:/home/why/catkin_ws/src:/home/why/sim_ws/src:/opt/ros/kinetic/share', 'TURTLEBOT_BASE': 'kobuki', '_': '/opt/ros/kinetic/bin/roslaunch', 'LC_IDENTIFICATION': 'zh_CN.UTF-8', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'TURTLEBOT_BATTERY': '/sys/class/power_supply/BAT0', 'ROS_MASTER_URI': 'http://localhost:11311', 'LC_TIME': 'zh_CN.UTF-8', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/why', 'QT4_IM_MODULE': 'fcitx', 'TURTLEBOT_STAGE_WORLD_FILE': '/opt/ros/kinetic/share/turtlebot_stage/maps/stage/maze.world', 'PKG_CONFIG_PATH': '/home/why/catkin_slam_ws/devel/lib/pkgconfig:/home/why/catkin_ws_practice/devel/lib/pkgconfig:/home/why/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig', 'HOME': '/home/why', 'LD_LIBRARY_PATH': '/home/why/catkin_slam_ws/devel/lib:/home/why/catkin_ws_practice/devel/lib:/home/why/catkin_ws/devel/lib:/home/why/sim_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/usr/local/cuda-10.0/lib64', 'LANG': 'en_US.UTF-8', 'ROS_LOG_FILENAME': '/home/why/.ros/log/9ec63c9e-7ec9-11e9-aa9a-7085c2882345/roslaunch-why-desktop-11960.log', 'LC_MONETARY': 'zh_CN.UTF-8', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'TURTLEBOT_SIMULATION': 'false', 'TURTLEBOT3_MODEL': 'burger', 'GTK_IM_MODULE': 'fcitx', 'VTE_VERSION': '4205', 'TURTLEBOT_SERIAL_PORT': '/dev/kobuki', 'TURTLEBOT_STAGE_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_stage/maps/maze.yaml', 'XDG_CURRENT_DESKTOP': 'Unity', 'TURTLEBOT_NAME': 'turtlebot', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'GNOME_KEYRING_PID': '', 'PAPERSIZE': 'a4', 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', 'ROS_DISTRO': 'kinetic', 'UNITY_HAS_3D_SUPPORT': 'true', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/why/catkin_slam_ws/devel/share/common-lisp:/home/why/catkin_ws_practice/devel/share/common-lisp:/home/why/catkin_ws/devel/share/common-lisp:/home/why/sim_ws/devel/share/common-lisp', 'QT_IM_MODULE': 'fcitx', 'LOGNAME': 'why', 'XDG_SEAT': 'seat0', 'GNOME_KEYRING_CONTROL': '', 'PATH': '/home/why/catkin_slam_ws/devel/bin:/home/why/catkin_ws/devel/bin:/opt/ros/kinetic/bin:/home/why/bin:/home/why/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-10.0/bin', 'TERM': 'xterm-256color', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'TURTLEBOT_STACKS': 'hexagons', 'TURTLEBOT_RAPP_PACKAGE_WHITELIST': '[rocon_apps, turtlebot_rapps]', 'SESSIONTYPE': 'gnome-session', 'IM_CONFIG_PHASE': '1', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/1681', 'GDM_LANG': 'en', 'LC_TELEPHONE': 'zh_CN.UTF-8', 'LC_MEASUREMENT': 'zh_CN.UTF-8', 'PWD': '/home/why', 'ROS_VERSION': '1'}
[roslaunch][INFO] 2019-05-25 16:50:58,592: starting in server mode
[roslaunch.parent][INFO] 2019-05-25 16:50:58,592: starting roslaunch parent run
[roslaunch][INFO] 2019-05-25 16:50:58,592: loading roscore config file /opt/ros/kinetic/etc/ros/roscore.xml
[roslaunch][INFO] 2019-05-25 16:50:58,800: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2019-05-25 16:50:58,800: loading config file /home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/launch/ros_mono.launch
[roslaunch][INFO] 2019-05-25 16:50:58,801: Added node of type [ORB_SLAM2/Mono] in namespace [/]
[roslaunch][INFO] 2019-05-25 16:50:58,801: ... selected machine [] for node of type [ORB_SLAM2/Mono]
[roslaunch.pmon][INFO] 2019-05-25 16:50:58,802: start_process_monitor: creating ProcessMonitor
[roslaunch.pmon][INFO] 2019-05-25 16:50:58,802: created process monitor <ProcessMonitor(ProcessMonitor-1, initial daemon)>
[roslaunch.pmon][INFO] 2019-05-25 16:50:58,802: start_process_monitor: ProcessMonitor started
[roslaunch.parent][INFO] 2019-05-25 16:50:58,802: starting parent XML-RPC server
[roslaunch.server][INFO] 2019-05-25 16:50:58,803: starting roslaunch XML-RPC server
[roslaunch.server][INFO] 2019-05-25 16:50:58,803: waiting for roslaunch XML-RPC server to initialize
[xmlrpc][INFO] 2019-05-25 16:50:58,803: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-05-25 16:50:58,803: Started XML-RPC server [http://why-desktop:38891/]
[xmlrpc][INFO] 2019-05-25 16:50:58,803: xml rpc node: starting XML-RPC server
[roslaunch][INFO] 2019-05-25 16:50:58,814: started roslaunch server http://why-desktop:38891/
[roslaunch.parent][INFO] 2019-05-25 16:50:58,814: ... parent XML-RPC server started
[roslaunch][INFO] 2019-05-25 16:50:58,814: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2019-05-25 16:50:58,815: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2019-05-25 16:50:58,815: ROS_MASTER_URI=http://localhost:11311
[roslaunch][INFO] 2019-05-25 16:50:58,817: setting /roslaunch/uris/host_why_desktop__38891' to http://why-desktop:38891/
[roslaunch][INFO] 2019-05-25 16:50:58,821: load_parameters starting ...
[roslaunch][INFO] 2019-05-25 16:50:58,823: ... load_parameters complete
[roslaunch][INFO] 2019-05-25 16:50:58,823: launch_nodes: launching local nodes ...
[roslaunch][INFO] 2019-05-25 16:50:58,823: ... preparing to launch node of type [ORB_SLAM2/Mono]
[roslaunch][INFO] 2019-05-25 16:50:58,823: create_node_process: package[ORB_SLAM2] type[Mono] machine[Machine(name[] env_loader[None] address[localhost] ssh_port[22] user[None] assignable[True] timeout[10.0])] master_uri[http://localhost:11311]
[roslaunch][INFO] 2019-05-25 16:50:58,823: process[ORB_SLAM2-1]: env[{'UPSTART_EVENTS': 'xsession started', 'XDG_SESSION_TYPE': 'x11', 'LC_PAPER': 'zh_CN.UTF-8', 'TURTLEBOT_STDR_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_stdr/maps/sparse_obstacles.yaml', 'SHELL': '/bin/bash', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'CLUTTER_IM_MODULE': 'xim', 'UNITY_DEFAULT_PROFILE': 'unity', 'UPSTART_INSTANCE': '', 'JOB': 'unity-settings-daemon', 'SESSION': 'ubuntu', 'XMODIFIERS': '@im=fcitx', 'TURTLEBOT_INTERACTIONS_LIST': '[turtlebot_bringup/admin.interactions, turtlebot_bringup/documentation.interactions, turtlebot_bringup/pairing.interactions, turtlebot_bringup/visualisation.interactions]', 'GTK2_MODULES': 'overlay-scrollbar', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_ADDRESS': 'zh_CN.UTF-8', 'PYTHONPATH': '/home/why/catkin_slam_ws/devel/lib/python2.7/dist-packages:/home/why/catkin_ws_practice/devel/lib/python2.7/dist-packages:/home/why/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages', 'COMPIZ_BIN_PATH': '/usr/bin/', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'QT_ACCESSIBILITY': '1', 'XDG_SESSION_ID': 'c2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-Wcfjkq9vsA', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'DESKTOP_SESSION': 'ubuntu', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'INSTANCE': '', 'TURTLEBOT_GAZEBO_WORLD_FILE': '/opt/ros/kinetic/share/turtlebot_gazebo/worlds/playground.world', 'TURTLEBOT_3D_SENSOR': 'asus_xtion_pro', 'TURTLEBOT_RAPP_PACKAGE_BLACKLIST': '[]', 'LC_NAME': 'zh_CN.UTF-8', 'XDG_MENU_PREFIX': 'gnome-', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LC_NUMERIC': 'zh_CN.UTF-8', 'TURTLEBOT_TYPE': 'turtlebot', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'TURTLEBOT_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_navigation/maps/willow-2010-02-18-0.10.yaml', 'USER': 'why', 'XDG_VTNR': '7', 'CMAKE_PREFIX_PATH': '/home/why/catkin_slam_ws/devel:/home/why/catkin_ws_practice/devel:/home/why/catkin_ws/devel:/home/why/sim_ws/devel:/opt/ros/kinetic', 'XAUTHORITY': '/home/why/.Xauthority', 'LANGUAGE': 'en', 'SESSION_MANAGER': 'local/why-desktop:@/tmp/.ICE-unix/1921,unix/why-desktop:/tmp/.ICE-unix/1921', 'SHLVL': '1', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'DISPLAY': ':0', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'WINDOWID': '90209485', 'GPG_AGENT_INFO': '/home/why/.gnupg/S.gpg-agent:0:1', 'XDG_SESSION_DESKTOP': 'ubuntu', 'GDMSESSION': 'ubuntu', 'UPSTART_JOB': 'unity7', 'TURTLEBOT_GAZEBO_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_gazebo/maps/playground.yaml', 'PKG_CONFIG_PATH': '/home/why/catkin_slam_ws/devel/lib/pkgconfig:/home/why/catkin_ws_practice/devel/lib/pkgconfig:/home/why/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig', 'ROS_PACKAGE_PATH': '/home/why/catkin_slam_ws/src:/home/why/catkin_ws_practice/src:/home/why/catkin_ws/src:/home/why/sim_ws/src:/opt/ros/kinetic/share', 'TURTLEBOT_BASE': 'kobuki', '_': '/opt/ros/kinetic/bin/roslaunch', 'GTK_IM_MODULE': 'fcitx', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'TURTLEBOT_BATTERY': '/sys/class/power_supply/BAT0', 'ROS_MASTER_URI': 'http://localhost:11311', 'LC_TIME': 'zh_CN.UTF-8', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/why', 'QT4_IM_MODULE': 'fcitx', 'TURTLEBOT_STAGE_WORLD_FILE': '/opt/ros/kinetic/share/turtlebot_stage/maps/stage/maze.world', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'HOME': '/home/why', 'LD_LIBRARY_PATH': '/home/why/catkin_slam_ws/devel/lib:/home/why/catkin_ws_practice/devel/lib:/home/why/catkin_ws/devel/lib:/home/why/sim_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/usr/local/cuda-10.0/lib64', 'LANG': 'en_US.UTF-8', 'ROS_LOG_FILENAME': '/home/why/.ros/log/9ec63c9e-7ec9-11e9-aa9a-7085c2882345/roslaunch-why-desktop-11960.log', 'LC_MONETARY': 'zh_CN.UTF-8', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'TURTLEBOT_SIMULATION': 'false', 'TURTLEBOT3_MODEL': 'burger', 'LC_IDENTIFICATION': 'zh_CN.UTF-8', 'VTE_VERSION': '4205', 'TURTLEBOT_SERIAL_PORT': '/dev/kobuki', 'TURTLEBOT_STAGE_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_stage/maps/maze.yaml', 'XDG_CURRENT_DESKTOP': 'Unity', 'TURTLEBOT_NAME': 'turtlebot', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'GNOME_KEYRING_PID': '', 'PAPERSIZE': 'a4', 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', 'ROS_DISTRO': 'kinetic', 'UNITY_HAS_3D_SUPPORT': 'true', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/why/catkin_slam_ws/devel/share/common-lisp:/home/why/catkin_ws_practice/devel/share/common-lisp:/home/why/catkin_ws/devel/share/common-lisp:/home/why/sim_ws/devel/share/common-lisp', 'QT_IM_MODULE': 'fcitx', 'LOGNAME': 'why', 'XDG_SEAT': 'seat0', 'PATH': '/home/why/catkin_slam_ws/devel/bin:/home/why/catkin_ws/devel/bin:/opt/ros/kinetic/bin:/home/why/bin:/home/why/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-10.0/bin', 'GNOME_KEYRING_CONTROL': '', 'TERM': 'xterm-256color', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'TURTLEBOT_STACKS': 'hexagons', 'TURTLEBOT_RAPP_PACKAGE_WHITELIST': '[rocon_apps, turtlebot_rapps]', 'SESSIONTYPE': 'gnome-session', 'IM_CONFIG_PHASE': '1', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/1681', 'GDM_LANG': 'en', 'LC_TELEPHONE': 'zh_CN.UTF-8', 'LC_MEASUREMENT': 'zh_CN.UTF-8', 'PWD': '/home/why', 'ROS_VERSION': '1'}]
[roslaunch][INFO] 2019-05-25 16:50:59,093: process[ORB_SLAM2-1]: args[[u'/home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/Mono', '/home/why/catkin_slam_ws/src/ORB_SLAM2/Vocabulary/ORBvoc.txt', '/home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/myslam.yaml', 'false', 'true', u'__name:=ORB_SLAM2']]
[roslaunch][INFO] 2019-05-25 16:50:59,093: ... created process [ORB_SLAM2-1]
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,094: ProcessMonitor.register[ORB_SLAM2-1]
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,094: ProcessMonitor.register[ORB_SLAM2-1] complete
[roslaunch][INFO] 2019-05-25 16:50:59,094: ... registered process [ORB_SLAM2-1]
[roslaunch][INFO] 2019-05-25 16:50:59,094: process[ORB_SLAM2-1]: starting os process
[roslaunch][INFO] 2019-05-25 16:50:59,094: process[ORB_SLAM2-1]: start w/ args [[u'/home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/Mono', '/home/why/catkin_slam_ws/src/ORB_SLAM2/Vocabulary/ORBvoc.txt', '/home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/myslam.yaml', 'false', 'true', u'__name:=ORB_SLAM2', u'__log:=/home/why/.ros/log/9ec63c9e-7ec9-11e9-aa9a-7085c2882345/ORB_SLAM2-1.log']]
[roslaunch][INFO] 2019-05-25 16:50:59,094: process[ORB_SLAM2-1]: cwd will be [/home/why/.ros]
[roslaunch][INFO] 2019-05-25 16:50:59,097: process[ORB_SLAM2-1]: started with pid [11977]
[roslaunch][INFO] 2019-05-25 16:50:59,097: ... successfully launched [ORB_SLAM2-1]
[roslaunch][INFO] 2019-05-25 16:50:59,097: ... launch_nodes complete
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,097: registrations completed <ProcessMonitor(ProcessMonitor-1, started daemon 139704537466624)>
[roslaunch.parent][INFO] 2019-05-25 16:50:59,097: ... roslaunch parent running, waiting for process exit
[roslaunch][INFO] 2019-05-25 16:50:59,097: spin
[roslaunch][ERROR] 2019-05-25 16:50:59,203: [ORB_SLAM2-1] process has died [pid 11977, exit code 127, cmd /home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/Mono /home/why/catkin_slam_ws/src/ORB_SLAM2/Vocabulary/ORBvoc.txt /home/why/catkin_slam_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/myslam.yaml false true __name:=ORB_SLAM2 __log:=/home/why/.ros/log/9ec63c9e-7ec9-11e9-aa9a-7085c2882345/ORB_SLAM2-1.log].
log file: /home/why/.ros/log/9ec63c9e-7ec9-11e9-aa9a-7085c2882345/ORB_SLAM2-1*.log
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,204: ProcessMonitor.unregister[ORB_SLAM2-1] starting
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,204: ProcessMonitor.unregister[ORB_SLAM2-1] complete
[roslaunch][INFO] 2019-05-25 16:50:59,204: all processes on machine have died, roslaunch will exit
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,305: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 139704537466624)>
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,305: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 139704537466624)>: remaining procs are []
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,307: ProcessMonitor exit: cleaning up data structures and signals
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,307: ProcessMonitor exit: pmon has shutdown
[roslaunch][INFO] 2019-05-25 16:50:59,398: process monitor is done spinning, initiating full shutdown
[roslaunch][INFO] 2019-05-25 16:50:59,398: runner.stop()
[roslaunch][INFO] 2019-05-25 16:50:59,398: shutting down processing monitor...
[roslaunch][INFO] 2019-05-25 16:50:59,398: shutting down processing monitor <ProcessMonitor(ProcessMonitor-1, stopped daemon 139704537466624)>
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,398: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, stopped daemon 139704537466624)>
[roslaunch][INFO] 2019-05-25 16:50:59,398: ... shutting down processing monitor complete
[roslaunch][INFO] 2019-05-25 16:50:59,398: done
[roslaunch.pmon][INFO] 2019-05-25 16:50:59,399: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, stopped daemon 139704537466624)>
[rospy.core][INFO] 2019-05-25 16:50:59,399: signal_shutdown [atexit]

**Comment by thien94** [comment]
To be honest I can't pinpoint the problem. Here are my suggestions:
* Comment out the code that you added then uncomment them bit by bit to see when the problem occurs.
* If your purpose is to use ORB-SLAM2 in ROS, I suggest this package: http://wiki.ros.org/orb_slam2_ros which has implemented everything you need.

**Comment by Derzhavin** [comment]
@why-freedom, did you solve this issue?

**Comment by barovjt** [comment]
@thien94 I am using the package you mention but it has the same problem.
